/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, GNU /usr/bin/c++ 13.3.0) */

module sar_top(valid, comp_data, clks, \sar_outp[0] , \sar_outp[1] , \sar_outp[2] , \sar_outp[3] , \sar_outp[4] , \sar_outp[5] , \sar_outp[6] , \sar_outp[7] , \sar_outn[0] , \sar_outn[1] , \sar_outn[2] , \sar_outn[3] , \sar_outn[4] , \sar_outn[5] , \sar_outn[6] , \sar_outn[7] );
  input valid;
  wire valid;
  input comp_data;
  wire comp_data;
  input clks;
  wire clks;
  output \sar_outp[0] ;
  wire \sar_outp[0] ;
  output \sar_outp[1] ;
  wire \sar_outp[1] ;
  output \sar_outp[2] ;
  wire \sar_outp[2] ;
  output \sar_outp[3] ;
  wire \sar_outp[3] ;
  output \sar_outp[4] ;
  wire \sar_outp[4] ;
  output \sar_outp[5] ;
  wire \sar_outp[5] ;
  output \sar_outp[6] ;
  wire \sar_outp[6] ;
  output \sar_outp[7] ;
  wire \sar_outp[7] ;
  output \sar_outn[0] ;
  wire \sar_outn[0] ;
  output \sar_outn[1] ;
  wire \sar_outn[1] ;
  output \sar_outn[2] ;
  wire \sar_outn[2] ;
  output \sar_outn[3] ;
  wire \sar_outn[3] ;
  output \sar_outn[4] ;
  wire \sar_outn[4] ;
  output \sar_outn[5] ;
  wire \sar_outn[5] ;
  output \sar_outn[6] ;
  wire \sar_outn[6] ;
  output \sar_outn[7] ;
  wire \sar_outn[7] ;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire \clkc[1] ;
  wire \clkc[2] ;
  wire \clkc[3] ;
  wire \clkc[4] ;
  wire \clkc[5] ;
  wire \clkc[6] ;
  wire \clkc[7] ;
  wire \clkc[8] ;
  sky130_fd_sc_hd__clkinv_1 _17_ (
    .A(\sar_outp[0] ),
    .Y(\sar_outn[0] )
  );
  sky130_fd_sc_hd__clkinv_1 _18_ (
    .A(\sar_outp[1] ),
    .Y(\sar_outn[1] )
  );
  sky130_fd_sc_hd__clkinv_1 _19_ (
    .A(\sar_outp[2] ),
    .Y(\sar_outn[2] )
  );
  sky130_fd_sc_hd__clkinv_1 _20_ (
    .A(\sar_outp[3] ),
    .Y(\sar_outn[3] )
  );
  sky130_fd_sc_hd__clkinv_1 _21_ (
    .A(\sar_outp[4] ),
    .Y(\sar_outn[4] )
  );
  sky130_fd_sc_hd__clkinv_1 _22_ (
    .A(\sar_outp[5] ),
    .Y(\sar_outn[5] )
  );
  sky130_fd_sc_hd__clkinv_1 _23_ (
    .A(\sar_outp[6] ),
    .Y(\sar_outn[6] )
  );
  sky130_fd_sc_hd__clkinv_1 _24_ (
    .A(\sar_outp[7] ),
    .Y(\sar_outn[7] )
  );
  sky130_fd_sc_hd__clkinv_1 _25_ (
    .A(clks),
    .Y(_00_)
  );
  sky130_fd_sc_hd__clkinv_1 _26_ (
    .A(clks),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _27_ (
    .A(clks),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _28_ (
    .A(clks),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _29_ (
    .A(clks),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _30_ (
    .A(clks),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _31_ (
    .A(clks),
    .Y(_06_)
  );
  sky130_fd_sc_hd__clkinv_1 _32_ (
    .A(clks),
    .Y(_07_)
  );
  sky130_fd_sc_hd__clkinv_1 _33_ (
    .A(clks),
    .Y(_08_)
  );
  sky130_fd_sc_hd__clkinv_1 _34_ (
    .A(clks),
    .Y(_09_)
  );
  sky130_fd_sc_hd__clkinv_1 _35_ (
    .A(clks),
    .Y(_10_)
  );
  sky130_fd_sc_hd__clkinv_1 _36_ (
    .A(clks),
    .Y(_11_)
  );
  sky130_fd_sc_hd__clkinv_1 _37_ (
    .A(clks),
    .Y(_12_)
  );
  sky130_fd_sc_hd__clkinv_1 _38_ (
    .A(clks),
    .Y(_13_)
  );
  sky130_fd_sc_hd__clkinv_1 _39_ (
    .A(clks),
    .Y(_14_)
  );
  sky130_fd_sc_hd__clkinv_1 _40_ (
    .A(clks),
    .Y(_15_)
  );
  sky130_fd_sc_hd__dfrtp_1 _41_ (
    .CLK(valid),
    .D(\clkc[1] ),
    .Q(\clkc[2] ),
    .RESET_B(_13_)
  );
  sky130_fd_sc_hd__dfstp_2 _42_ (
    .CLK(\clkc[2] ),
    .D(comp_data),
    .Q(\sar_outp[6] ),
    .SET_B(_03_)
  );
  sky130_fd_sc_hd__dfrtp_1 _43_ (
    .CLK(valid),
    .D(\clkc[2] ),
    .Q(\clkc[3] ),
    .RESET_B(_12_)
  );
  sky130_fd_sc_hd__dfstp_2 _44_ (
    .CLK(\clkc[3] ),
    .D(comp_data),
    .Q(\sar_outp[5] ),
    .SET_B(_02_)
  );
  sky130_fd_sc_hd__dfrtp_1 _45_ (
    .CLK(valid),
    .D(\clkc[3] ),
    .Q(\clkc[4] ),
    .RESET_B(_11_)
  );
  sky130_fd_sc_hd__dfstp_2 _46_ (
    .CLK(\clkc[4] ),
    .D(comp_data),
    .Q(\sar_outp[4] ),
    .SET_B(_01_)
  );
  sky130_fd_sc_hd__dfrtp_1 _47_ (
    .CLK(valid),
    .D(\clkc[4] ),
    .Q(\clkc[5] ),
    .RESET_B(_09_)
  );
  sky130_fd_sc_hd__dfstp_2 _48_ (
    .CLK(\clkc[5] ),
    .D(comp_data),
    .Q(\sar_outp[3] ),
    .SET_B(_00_)
  );
  sky130_fd_sc_hd__dfrtp_1 _49_ (
    .CLK(valid),
    .D(\clkc[5] ),
    .Q(\clkc[6] ),
    .RESET_B(_08_)
  );
  sky130_fd_sc_hd__dfstp_2 _50_ (
    .CLK(\clkc[6] ),
    .D(comp_data),
    .Q(\sar_outp[2] ),
    .SET_B(_14_)
  );
  sky130_fd_sc_hd__dfrtp_1 _51_ (
    .CLK(valid),
    .D(\clkc[6] ),
    .Q(\clkc[7] ),
    .RESET_B(_07_)
  );
  sky130_fd_sc_hd__dfstp_2 _52_ (
    .CLK(\clkc[7] ),
    .D(comp_data),
    .Q(\sar_outp[1] ),
    .SET_B(_10_)
  );
  sky130_fd_sc_hd__dfrtp_1 _53_ (
    .CLK(valid),
    .D(\clkc[7] ),
    .Q(\clkc[8] ),
    .RESET_B(_05_)
  );
  sky130_fd_sc_hd__dfstp_2 _54_ (
    .CLK(\clkc[8] ),
    .D(comp_data),
    .Q(\sar_outp[0] ),
    .SET_B(_06_)
  );
  sky130_fd_sc_hd__dfrtp_1 _55_ (
    .CLK(valid),
    .D(_16_),
    .Q(\clkc[1] ),
    .RESET_B(_15_)
  );
  sky130_fd_sc_hd__dfstp_2 _56_ (
    .CLK(\clkc[1] ),
    .D(comp_data),
    .Q(\sar_outp[7] ),
    .SET_B(_04_)
  );
  sky130_fd_sc_hd__conb_1 _57_ (
    .HI(_16_)
  );
endmodule
